#!/bin/bash

NODE_VERSION=12-alpine3.9
NG_CLI_VERSION=10.0.7
NG_SCHEMATICS_VERSION=0.1000.6

docker build \
  --build-arg NODE_VERSION=$NODE_VERSION \
  --build-arg NG_CLI_VERSION=$NG_CLI_VERSION \
  --build-arg NG_SCHEMATICS_VERSION=$NG_SCHEMATICS_VERSION \
  -t samherrmann/angular-cli:$DOCKER_TAG .
